# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: ../../analysis_options.yaml

linter:
  rules:
    - prefer_relative_imports
