name: danger_test
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  path: ^1.8.0
  danger_core:
    path: packages/danger_core
  danger_plugin_dart_test:
    path: packages/danger_plugin_dart_test
