name: danger_plugin_example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  uuid: ^3.0.1

dev_dependencies:
  pedantic: ^1.9.0
  path: ^1.8.0
  danger_core:
    path: ../../../packages/danger_core
