name: danger_plugin_dart_test
description: A starting point for Dart libraries or applications.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  danger_core:
    path: ../danger_core

dev_dependencies:
  test: ^1.14.4
