name: danger_plugin_dart_test
description: A Danger Dart plugin to process test result.
version: 2.0.0
homepage: https://github.com/danger/dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.3
  # danger_core: ">= 1.0.0 < 2.0.0"
  danger_core:
    path: ../danger_core

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
