name: danger_dart
description: Danger Dart, tool to help you reviewing the code.
version: 2.0.0
homepage: https://github.com/danger/dart

executables:
  danger_dart:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.10.0
  args: ^2.4.2
  process_run: ^0.13.1
  fimber: ^0.7.0
  path: ^1.8.3
  # danger_core: ">= 1.0.0 < 2.0.0"
  danger_core:
    path: ../danger_core

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
  mockito: ^5.4.2
  build_runner: ^2.4.6
