name: danger_dart
description: A simple command-line application.
version: 0.0.1
homepage: https://github.com/danger/danger.dart

executables:
  danger_dart:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  args: ^2.0.0
  process_run: ^0.12.0+1
  fimber: ^0.6.1
  path: ^1.8.0
  # danger_core: ">= 0.0.1 < 2.0.0"
  danger_core:
    path: ../danger_core

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  mockito: ^4.1.4
