# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Danger compatibility

on: pull_request

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Fetch master
        run: git fetch origin master:master

      - uses: actions/setup-node@v1

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install Danger-js
        run: npm install -g danger

      - name: Activate command
        run: dart pub global activate --source path packages/danger_dart/

      - name: Install danger_core dependencies
        run: dart pub get
        working-directory: packages/danger_core/

      - name: Install danger_dart dependencies
        run: dart pub get
        working-directory: packages/danger_dart/

      - name: Install app (non nullsafety) dependencies
        run: dart pub get
        working-directory: example/pre_nullsafety/

      - name: Run danger local (non nullsafety)
        run: danger_dart local
        working-directory: example/pre_nullsafety/

      - name: Install app dependencies (nullsafety)
        run: dart pub get
        working-directory: example/target_nullsafety/

      - name: Run danger local (nullsafety)
        run: danger_dart local
        working-directory: example/target_nullsafety/

      - name: Install plugin dependencies
        run: dart pub get
        working-directory: example/with_plugin/danger_plugin_example/

      - name: Install plugin example dependencies
        run: dart pub get
        working-directory: example/with_plugin/

      - name: Run danger local (with plugin)
        run: danger_dart local
        working-directory: example/with_plugin/

